task_4_3_3: details page
SoEasy/surf-flutter-course-sannikov pull request #10
Opened 2020-12-08 20:54 UTC by SoEasy

2020-12-09 09:53 UTC, artem-zaitsev requested changes
Поправьте замечания из этого и предыдущих пулл реквестов.

Вы довольно неплохо пишете, код читаемый.

Особенно сделайте поле в моках еще одно. Хоть напрямую к заданию не относится, но в реальном мире - это был бы довольно неплохой баг.

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +enum PlacesButtonSize {
док

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +enum PlacesButtonType {
док

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +class PlacesButton extends StatelessWidget {
док

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +class PlacesButton extends StatelessWidget {
Хотя бы описание  что именно жто за экран

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +enum PlacesButtonType {
Для чего эти энамы?

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +        new Expanded(
new - устаревший вариант из Dart 1.0

2020-12-09 09:53 UTC, artem-zaitsev commented on lib/ui/screen/sight_details.dart
> +                              'Закрыто до 16:00',
Как я понимаю здесь текст захардкожен, так как его нет в моковых данных?

Так как это все же часть информации о месте, то лучше внести это как поле.

2020-12-10 11:14 UTC, Evoswork commented on lib/ui/screen/sight_details.dart
> +                child: Column(
разбейте код на отдельны методы

2020-12-10 11:17 UTC, Evoswork commented on lib/ui/screen/sight_details.dart
> +                    this.sight.url,
на макете есть кнопка "назад"

2020-12-10 11:18 UTC, SoEasy commented on lib/ui/screen/sight_details.dart
> +                child: Column(
@Evoswork
На виджеты? Или на приватные методы виджета, возвращающие виджеты?

2020-12-10 11:19 UTC, Evoswork commented on lib/shared/places_colors.dart
> +  static Color get White_PrimaryButton {
camelCase принято называть цвета
в другом пр было указано, даже если он ещё не принят, то стоит сразу писать без ошибок в новом пр

2020-12-10 11:20 UTC, Evoswork commented on lib/ui/screen/sight_card.dart
> +                  )),
trailing comma

2020-12-10 11:21 UTC, Evoswork commented on lib/ui/screen/sight_details.dart
> +          color: PlacesColors.White_PrimaryButton),
trailing comma

2020-12-10 11:22 UTC, SoEasy commented on lib/shared/places_colors.dart
> +  static Color get White_PrimaryButton {
@Evoswork 
Выше, в комменте к классу я написал, что цвета именуются в соответствии с фигмой.
Не хочется разводить зоопарк - в фигме одни названия, в коде другие.
Но ладно, исправлю. Просто обычно такие вещи держат в соответствии(например при автогенерации кода из Фигмы)

2020-12-10 20:23 UTC, SoEasy commented on lib/ui/screen/sight_details.dart
> +          color: PlacesColors.White_PrimaryButton),
done

2020-12-10 20:23 UTC, SoEasy commented on lib/ui/screen/sight_card.dart
> +                  )),
done

2020-12-10 20:23 UTC, SoEasy commented on lib/shared/places_colors.dart
> +  static Color get White_PrimaryButton {
done

2020-12-10 20:23 UTC, SoEasy commented on lib/ui/screen/sight_details.dart
> +                    this.sight.url,
done

2020-12-10 20:23 UTC, SoEasy commented on lib/ui/screen/sight_details.dart
> +                child: Column(
done

2020-12-11 15:00 UTC, artem-zaitsev approved these changes

2020-12-13 13:03 UTC, merged